# Init

In [1]:
%run ~/repos/aou_disease_prediction_2/aou_scripts/Setting_Env_Variables.ipynb

Successfully set WORKSPACE_CDR to: wb-silky-artichoke-2408.C2024Q3R8
Found bucket: id=aou-tutorial-notebooks, bucketName=aou-tutorial-notebooks-wb-sunny-radish-6214
Found bucket: id=bhs-example-notebooks, bucketName=bhs-example-notebooks-wb-frosty-coconut-5800
Found bucket: id=ckd-esrd-cohort-20250505, bucketName=ckd-esrd-cohort-20250505-wb-glacial-acorn-1350
Found bucket: id=temporary-workspace-bucket, bucketName=temporary-workspace-bucket-wb-glacial-acorn-1350
Found bucket: id=vwb-aou-datasets-controlled, bucketName=vwb-aou-datasets-controlled
Found bucket: id=workspace-bucket, bucketName=workspace-bucket-wb-glacial-acorn-1350

Variables extracted:
GOOGLE_CLOUD_PROJECT: wb-glacial-acorn-1350
WORKSPACE_BUCKET: gs://workspace-bucket-wb-glacial-acorn-1350
WORKSPACE_TEMP_BUCKET: gs://temporary-workspace-bucket-wb-glacial-acorn-1350
WORKSPACE_CDR: wb-silky-artichoke-2408.C2024Q3R8

✅ Saved to /home/jupyter/.bashrc
C2024Q3R5_serology BQ_DATASET
C2024Q3R8 BQ_DATASET
C2024Q3R9 BQ_DATASET
C_V8_R2_offcycle_etm BQ_DATASET
C_V8_R2_offcycle_mhwb BQ_DATASET
C_V8_R3_aou_biospecimen BQ_DATASET
aou-tutorial-notebooks GCS_BUCKET
aou_disease_prediction GIT_REPO
aou_disease_prediction_2 GIT_REPO
bhs-example-notebooks GCS_BUCKET
ckd-esrd-cohort-20250505 GCS_BUCKET
prep_C2024Q3R8 BQ_DATASET
prep_C2024Q3R9 BQ_DATASET
temporary-workspace-bucket GCS_BUCKET
vwb-aou-datasets-controlled GCS_BUCKET
workspace-bucket GCS_BUCKET
GOOGLE_CLOUD_PROJECT = wb-glacial-acorn-1350
WORKSPACE_BUCKET = gs://workspace-bucket-wb-glacial-acorn-1350

wb-silky-artichoke-2408.C2024Q3R8

gs://temporary-workspace-bucket-wb-glacial-acorn-1350

In [2]:
%run ~/repos/aou_disease_prediction_2/aou_scripts/Setting_Env_Variables_p2.ipynb

GOOGLE_CLOUD_PROJECT = wb-glacial-acorn-1350
WORKSPACE_BUCKET = gs://workspace-bucket-wb-glacial-acorn-1350

wb-silky-artichoke-2408.C2024Q3R8

gs://temporary-workspace-bucket-wb-glacial-acorn-1350

Done! /home/jupyter/repos/aou_disease_prediction_2/aou_scripts/Setting_Env_Variables_p2.R now contains 5 variables.

In [3]:
dataset = %env WORKSPACE_CDR
dataset

'wb-silky-artichoke-2408.C2024Q3R8'

# Queries
## Actual queries

In [1]:
# import statements for the software packages and modules we will use in this tutorial
import os
import numpy as np
import pandas as pd
import plotnine
from plotnine import *
import pandas_gbq
from datetime import datetime
from google.cloud import bigquery

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [6]:
# CKD 3, 4, 5, ESRD Patients and their disease history
query = f"""
WITH target_cohort AS (
    SELECT DISTINCT person_id
    FROM {dataset}.condition_occurrence
    WHERE condition_concept_id IN (443597, 443612, 443611, 193782)
)

SELECT 
    co.person_id,
    -- 1. Disease Name
    c1.concept_name AS condition_name,
    co.condition_start_date,
    co.condition_end_date,
    -- 2. Type Name (e.g., "EHR Chief Complaint" or "Claim")
    c2.concept_name AS condition_type_name,
FROM {dataset}.condition_occurrence co
JOIN target_cohort tc ON co.person_id = tc.person_id
-- Join for the main disease name
JOIN {dataset}.concept c1 ON co.condition_concept_id = c1.concept_id
-- Join for the record type
LEFT JOIN {dataset}.concept c2 ON co.condition_type_concept_id = c2.concept_id
ORDER BY co.person_id, co.condition_start_date;
"""

ckd_patients_disease_history = pandas_gbq.read_gbq(query)

Downloading:   0%|          |

Downloading:   0%|          |

Downloading:   1%|          |

Downloading:   1%|          |

Downloading:   1%|          |

Downloading:   1%|▏         |

Downloading:   2%|▏         |

Downloading:   2%|▏         |

Downloading:   2%|▏         |

Downloading:   2%|▏         |

Downloading:   3%|▎         |

Downloading:   3%|▎         |

Downloading:   3%|▎         |

Downloading:   3%|▎         |

Downloading:   4%|▎         |

Downloading:   4%|▍         |

Downloading:   4%|▍         |

Downloading:   4%|▍         |

Downloading:   5%|▍         |

Downloading:   5%|▍         |

Downloading:   5%|▌         |

Downloading:   5%|▌         |

Downloading:   6%|▌         |

Downloading:   6%|▌         |

Downloading:   6%|▌         |

Downloading:   6%|▋         |

Downloading:   7%|▋         |

Downloading:   7%|▋         |

Downloading:   7%|▋         |

Downloading:   7%|▋         |

Downloading:   8%|▊         |

Downloading:   8%|▊         |

Downloading:   8%|▊         |

Downloading:   8%|▊         |

Downloading:   9%|▊         |

Downloading:   9%|▉         |

Downloading:   9%|▉         |

Downloading:   9%|▉         |

Downloading:  10%|▉         |

Downloading:  10%|█         |

Downloading:  10%|█         |

Downloading:  11%|█         |

Downloading:  11%|█         |

Downloading:  11%|█         |

Downloading:  11%|█▏        |

Downloading:  12%|█▏        |

Downloading:  12%|█▏        |

Downloading:  12%|█▏        |

Downloading:  12%|█▏        |

Downloading:  13%|█▎        |

Downloading:  13%|█▎        |

Downloading:  13%|█▎        |

Downloading:  13%|█▎        |

Downloading:  14%|█▎        |

Downloading:  14%|█▍        |

Downloading:  14%|█▍        |

Downloading:  14%|█▍        |

Downloading:  15%|█▍        |

Downloading:  15%|█▍        |

Downloading:  15%|█▌        |

Downloading:  15%|█▌        |

Downloading:  16%|█▌        |

Downloading:  16%|█▌        |

Downloading:  16%|█▌        |

Downloading:  16%|█▋        |

Downloading:  17%|█▋        |

Downloading:  17%|█▋        |

Downloading:  17%|█▋        |

Downloading:  17%|█▋        |

Downloading:  18%|█▊        |

Downloading:  18%|█▊        |

Downloading:  18%|█▊        |

Downloading:  18%|█▊        |

Downloading:  19%|█▊        |

Downloading:  19%|█▉        |

Downloading:  19%|█▉        |

Downloading:  19%|█▉        |

Downloading:  20%|█▉        |

Downloading:  20%|██        |

Downloading:  20%|██        |

Downloading:  21%|██        |

Downloading:  21%|██        |

Downloading:  21%|██        |

Downloading:  21%|██▏       |

Downloading:  22%|██▏       |

Downloading:  22%|██▏       |

Downloading:  22%|██▏       |

Downloading:  22%|██▏       |

Downloading:  23%|██▎       |

Downloading:  23%|██▎       |

Downloading:  23%|██▎       |

Downloading:  23%|██▎       |

Downloading:  24%|██▎       |

Downloading:  24%|██▍       |

Downloading:  24%|██▍       |

Downloading:  24%|██▍       |

Downloading:  25%|██▍       |

Downloading:  25%|██▍       |

Downloading:  25%|██▌       |

Downloading:  25%|██▌       |

Downloading:  26%|██▌       |

Downloading:  26%|██▌       |

Downloading:  26%|██▌       |

Downloading:  26%|██▋       |

Downloading:  27%|██▋       |

Downloading:  27%|██▋       |

Downloading:  27%|██▋       |

Downloading:  27%|██▋       |

Downloading:  28%|██▊       |

Downloading:  28%|██▊       |

Downloading:  28%|██▊       |

Downloading:  28%|██▊       |

Downloading:  29%|██▊       |

Downloading:  29%|██▉       |

Downloading:  29%|██▉       |

Downloading:  29%|██▉       |

Downloading:  30%|██▉       |

Downloading:  30%|███       |

Downloading:  30%|███       |

Downloading:  31%|███       |

Downloading:  31%|███       |

Downloading:  31%|███       |

Downloading:  31%|███▏      |

Downloading:  32%|███▏      |

Downloading:  32%|███▏      |

Downloading:  32%|███▏      |

Downloading:  32%|███▏      |

Downloading:  33%|███▎      |

Downloading:  33%|███▎      |

Downloading:  33%|███▎      |

Downloading:  33%|███▎      |

Downloading:  34%|███▎      |

Downloading:  34%|███▍      |

Downloading:  34%|███▍      |

Downloading:  34%|███▍      |

Downloading:  35%|███▍      |

Downloading:  35%|███▍      |

Downloading:  35%|███▌      |

Downloading:  35%|███▌      |

Downloading:  36%|███▌      |

Downloading:  36%|███▌      |

Downloading:  36%|███▌      |

Downloading:  36%|███▋      |

Downloading:  37%|███▋      |

Downloading:  37%|███▋      |

Downloading:  37%|███▋      |

Downloading:  37%|███▋      |

Downloading:  38%|███▊      |

Downloading:  38%|███▊      |

Downloading:  38%|███▊      |

Downloading:  38%|███▊      |

Downloading:  39%|███▊      |

Downloading:  39%|███▉      |

Downloading:  39%|███▉      |

Downloading:  40%|███▉      |

Downloading:  40%|███▉      |

Downloading:  40%|████      |

Downloading:  40%|████      |

Downloading:  41%|████      |

Downloading:  41%|████      |

Downloading:  41%|████      |

Downloading:  41%|████▏     |

Downloading:  42%|████▏     |

Downloading:  42%|████▏     |

Downloading:  42%|████▏     |

Downloading:  42%|████▏     |

Downloading:  43%|████▎     |

Downloading:  43%|████▎     |

Downloading:  43%|████▎     |

Downloading:  43%|████▎     |

Downloading:  44%|████▎     |

Downloading:  44%|████▍     |

Downloading:  44%|████▍     |

Downloading:  44%|████▍     |

Downloading:  45%|████▍     |

Downloading:  45%|████▍     |

Downloading:  45%|████▌     |

Downloading:  45%|████▌     |

Downloading:  46%|████▌     |

Downloading:  46%|████▌     |

Downloading:  46%|████▌     |

Downloading:  46%|████▋     |

Downloading:  47%|████▋     |

Downloading:  47%|████▋     |

Downloading:  47%|████▋     |

Downloading:  47%|████▋     |

Downloading:  48%|████▊     |

Downloading:  48%|████▊     |

Downloading:  48%|████▊     |

Downloading:  48%|████▊     |

Downloading:  49%|████▊     |

Downloading:  49%|████▉     |

Downloading:  49%|████▉     |

Downloading:  50%|████▉     |

Downloading:  50%|████▉     |

Downloading:  50%|█████     |

Downloading:  50%|█████     |

Downloading:  51%|█████     |

Downloading:  51%|█████     |

Downloading:  51%|█████     |

Downloading:  51%|█████▏    |

Downloading:  52%|█████▏    |

Downloading:  52%|█████▏    |

Downloading:  52%|█████▏    |

Downloading:  52%|█████▏    |

Downloading:  53%|█████▎    |

Downloading:  53%|█████▎    |

Downloading:  53%|█████▎    |

Downloading:  53%|█████▎    |

Downloading:  54%|█████▎    |

Downloading:  54%|█████▍    |

Downloading:  54%|█████▍    |

Downloading:  54%|█████▍    |

Downloading:  55%|█████▍    |

Downloading:  55%|█████▍    |

Downloading:  55%|█████▌    |

Downloading:  55%|█████▌    |

Downloading:  56%|█████▌    |

Downloading:  56%|█████▌    |

Downloading:  56%|█████▌    |

Downloading:  56%|█████▋    |

Downloading:  57%|█████▋    |

Downloading:  57%|█████▋    |

Downloading:  57%|█████▋    |

Downloading:  57%|█████▋    |

Downloading:  58%|█████▊    |

Downloading:  58%|█████▊    |

Downloading:  58%|█████▊    |

Downloading:  58%|█████▊    |

Downloading:  59%|█████▊    |

Downloading:  59%|█████▉    |

Downloading:  59%|█████▉    |

Downloading:  60%|█████▉    |

Downloading:  60%|█████▉    |

Downloading:  60%|██████    |

Downloading:  60%|██████    |

Downloading:  61%|██████    |

Downloading:  61%|██████    |

Downloading:  61%|██████    |

Downloading:  61%|██████▏   |

Downloading:  62%|██████▏   |

Downloading:  62%|██████▏   |

Downloading:  62%|██████▏   |

Downloading:  62%|██████▏   |

Downloading:  63%|██████▎   |

Downloading:  63%|██████▎   |

Downloading:  63%|██████▎   |

Downloading:  63%|██████▎   |

Downloading:  64%|██████▎   |

Downloading:  64%|██████▍   |

Downloading:  64%|██████▍   |

Downloading:  64%|██████▍   |

Downloading:  65%|██████▍   |

Downloading:  65%|██████▍   |

Downloading:  65%|██████▌   |

Downloading:  65%|██████▌   |

Downloading:  66%|██████▌   |

Downloading:  66%|██████▌   |

Downloading:  66%|██████▌   |

Downloading:  66%|██████▋   |

Downloading:  67%|██████▋   |

Downloading:  67%|██████▋   |

Downloading:  67%|██████▋   |

Downloading:  67%|██████▋   |

Downloading:  68%|██████▊   |

Downloading:  68%|██████▊   |

Downloading:  68%|██████▊   |

Downloading:  68%|██████▊   |

Downloading:  69%|██████▊   |

Downloading:  69%|██████▉   |

Downloading:  69%|██████▉   |

Downloading:  70%|██████▉   |

Downloading:  70%|██████▉   |

Downloading:  70%|███████   |

Downloading:  70%|███████   |

Downloading:  71%|███████   |

Downloading:  71%|███████   |

Downloading:  71%|███████   |

Downloading:  71%|███████▏  |

Downloading:  72%|███████▏  |

Downloading:  72%|███████▏  |

Downloading:  72%|███████▏  |

Downloading:  72%|███████▏  |

Downloading:  73%|███████▎  |

Downloading:  73%|███████▎  |

Downloading:  73%|███████▎  |

Downloading:  73%|███████▎  |

Downloading:  74%|███████▎  |

Downloading:  74%|███████▍  |

Downloading:  74%|███████▍  |

Downloading:  74%|███████▍  |

Downloading:  75%|███████▍  |

Downloading:  75%|███████▍  |

Downloading:  75%|███████▌  |

Downloading:  75%|███████▌  |

Downloading:  76%|███████▌  |

Downloading:  76%|███████▌  |

Downloading:  76%|███████▌  |

Downloading:  76%|███████▋  |

Downloading:  77%|███████▋  |

Downloading:  77%|███████▋  |

Downloading:  77%|███████▋  |

Downloading:  77%|███████▋  |

Downloading:  78%|███████▊  |

Downloading:  78%|███████▊  |

Downloading:  78%|███████▊  |

Downloading:  78%|███████▊  |

Downloading:  79%|███████▉  |

Downloading:  79%|███████▉  |

Downloading:  79%|███████▉  |

Downloading:  80%|███████▉  |

Downloading:  80%|███████▉  |

Downloading:  80%|████████  |

Downloading:  80%|████████  |

Downloading:  81%|████████  |

Downloading:  81%|████████  |

Downloading:  81%|████████  |

Downloading:  81%|████████▏ |

Downloading:  82%|████████▏ |

Downloading:  82%|████████▏ |

Downloading:  82%|████████▏ |

Downloading:  82%|████████▏ |

Downloading:  83%|████████▎ |

Downloading:  83%|████████▎ |

Downloading:  83%|████████▎ |

Downloading:  83%|████████▎ |

Downloading:  84%|████████▎ |

Downloading:  84%|████████▍ |

Downloading:  84%|████████▍ |

Downloading:  84%|████████▍ |

Downloading:  85%|████████▍ |

Downloading:  85%|████████▍ |

Downloading:  85%|████████▌ |

Downloading:  85%|████████▌ |

Downloading:  86%|████████▌ |

Downloading:  86%|████████▌ |

Downloading:  86%|████████▌ |

Downloading:  86%|████████▋ |

Downloading:  87%|████████▋ |

Downloading:  87%|████████▋ |

Downloading:  87%|████████▋ |

Downloading:  87%|████████▋ |

Downloading:  88%|████████▊ |

Downloading:  88%|████████▊ |

Downloading:  88%|████████▊ |

Downloading:  88%|████████▊ |

Downloading:  89%|████████▉ |

Downloading:  89%|████████▉ |

Downloading:  89%|████████▉ |

Downloading:  90%|████████▉ |

Downloading:  90%|████████▉ |

Downloading:  90%|█████████ |

Downloading:  90%|█████████ |

Downloading:  91%|█████████ |

Downloading:  91%|█████████ |

Downloading:  91%|█████████ |

Downloading:  91%|█████████▏|

Downloading:  92%|█████████▏|

Downloading:  92%|█████████▏|

Downloading:  92%|█████████▏|

Downloading:  92%|█████████▏|

Downloading:  93%|█████████▎|

Downloading:  93%|█████████▎|

Downloading:  93%|█████████▎|

Downloading:  93%|█████████▎|

Downloading:  94%|█████████▎|

Downloading:  94%|█████████▍|

Downloading:  94%|█████████▍|

Downloading:  94%|█████████▍|

Downloading:  95%|█████████▍|

Downloading:  95%|█████████▍|

Downloading:  95%|█████████▌|

Downloading:  95%|█████████▌|

Downloading:  96%|█████████▌|

Downloading:  96%|█████████▌|

Downloading:  96%|█████████▌|

Downloading:  96%|█████████▋|

Downloading:  97%|█████████▋|

Downloading:  97%|█████████▋|

Downloading:  97%|█████████▋|

Downloading:  97%|█████████▋|

Downloading:  98%|█████████▊|

Downloading:  98%|█████████▊|

Downloading:  98%|█████████▊|

Downloading:  99%|█████████▊|

Downloading:  99%|█████████▉|

Downloading:  99%|█████████▉|

Downloading:  99%|█████████▉|

Downloading: 100%|█████████▉|

Downloading: 100%|█████████▉|

Downloading: 100%|██████████|

Downloading: 100%|██████████|

In [8]:
with pd.option_context('display.max_colwidth', None, 'display.max_columns', None, ):
    display(ckd_patients_disease_history.head(5))

,person_id,condition_name,condition_start_date,condition_end_date,condition_type_name
0,1000105,Shoulder joint pain,2009-06-22,NaT,EHR problem list entry
1,1000105,Neck pain,2009-06-22,NaT,Primary Condition
2,1000105,Allergic rhinitis,2010-04-05,NaT,EHR problem list entry
3,1000105,Allergic rhinitis,2010-04-05,NaT,Secondary Condition
4,1000105,Otitis media,2010-04-05,NaT,Primary Condition

In [9]:
ckd_patients_disease_history.shape

(27288397, 5)

In [10]:
# Save ckd_patients_disease_history to a parquet file
ckd_patients_disease_history.to_parquet("ckd_patients_disease_history.parquet", index=False)

In [11]:
# Dedupe person_id and save it to a .txt file
ckd_patients_disease_history["person_id"].drop_duplicates().to_csv("ckd_patients.txt", index=False, header=False)

In [ ]:
# Read in ckd_patients.txt as a df, duplicate the column once. 
patients = pd.read_csv("ckd_patients.txt", header=None, names=["person_id"])
patients["person_id_dup"] = patients["person_id"]

# Rename the first column #FID, the second column IID.
patients.columns = ["#FID", "IID"]
patients.to_csv("ckd_patients_for_plink.txt", index=False, sep="\s")

## bigquery module explorations

In [6]:
query = f"""
SELECT
    COUNT(DISTINCT person_id) AS n_participants, 'Genomics' as data
FROM {dataset}.cb_search_person 
WHERE has_whole_genome_variant = 1 OR has_array_data = 1
"""
genomics_count_df = pandas_gbq.read_gbq(query)
genomics_count_df

Downloading:   0%|          |

Downloading: 100%|██████████|

   n_participants      data
0          447281  Genomics

In [6]:
# CKD 3, 4, 5, ESRD Patients and their disease history
query = f"""
WITH target_cohort AS (
    SELECT DISTINCT person_id
    FROM {dataset}.condition_occurrence
    WHERE condition_concept_id IN (443597, 443612, 443611, 193782)
)

SELECT 
    co.person_id,
    -- 1. Disease Name
    c1.concept_name AS condition_name,
    co.condition_start_date,
    co.condition_end_date,
    -- 2. Type Name (e.g., "EHR Chief Complaint" or "Claim")
    c2.concept_name AS condition_type_name,
    -- 3. Status Name (e.g., "Final diagnosis")
    c3.concept_name AS condition_status_name,
    --c4.concept_name AS source_concept_name,
    v.vocabulary_name AS source_vocabulary,
    co.condition_source_value,
    --co.condition_occurrence_id,
    co.condition_concept_id,
    co.condition_type_concept_id,
    co.condition_status_concept_id,
    c5.concept_name as visit_concept_name,
    vo.visit_concept_id,
    c6.concept_name as visit_type_concept_name,
    vo.visit_type_concept_id
FROM {dataset}.condition_occurrence co
JOIN target_cohort tc ON co.person_id = tc.person_id
-- Join for the main disease name
JOIN {dataset}.concept c1 ON co.condition_concept_id = c1.concept_id
-- Join for the record type
LEFT JOIN {dataset}.concept c2 ON co.condition_type_concept_id = c2.concept_id
-- Join for the clinical status
LEFT JOIN {dataset}.concept c3 ON co.condition_status_concept_id = c3.concept_id
-- Join 4: Source Concept Name
LEFT JOIN {dataset}.concept c4 ON co.condition_source_concept_id = c4.concept_id
-- Join 5: Vocabulary Name (e.g., identifying if it's ICD-9, ICD-10, etc.)
LEFT JOIN {dataset}.vocabulary v ON c4.vocabulary_id = v.vocabulary_id
-- Join 6: visit name and visit type
LEFT JOIN {dataset}.visit_occurrence vo ON co.visit_occurrence_id = vo.visit_occurrence_id
JOIN {dataset}.concept c5 on vo.visit_concept_id = c5.concept_id
JOIN {dataset}.concept c6 on vo.visit_type_concept_id = c6.concept_id
ORDER BY co.person_id, co.condition_start_date;
"""

ckd_patients_disease_history = pandas_gbq.read_gbq(query)

In [14]:
ckd_patients_disease_history_deduped = ckd_patients_disease_history.drop_duplicates(
    subset=["person_id", "condition_name", "condition_start_date", "condition_end_date"],
    keep="first"
).reset_index(drop=True)

In [ ]:
with pd.option_context('display.max_colwidth', None, 'display.max_columns', None, ):
    display(ckd_patients_disease_history.head(25))

In [53]:
ckd_patients_disease_history.condition_status_name.value_counts()

condition_status_name
No matching concept                                                                                      9881090
Final diagnosis (discharge)                                                                              3132034
Secondary diagnosis                                                                                       855998
Primary diagnosis                                                                                         621779
Suggested billing diagnosis                                                                               393392
                                                                                                          ...
Local infection due to central venous catheter                                                                 1
Follicular lymphoma grade IIIb, unspecified site                                                               1
Unspecified obstruction of Eustachian tube, bilateral                                                          1
Other fracture of unspecified lumbar vertebra, subsequent encounter for fracture with routine healing          1
Edema of right upper eyelid                                                                                    1
Name: count, Length: 13508, dtype: int64

In [52]:
ckd_patients_disease_history.source_vocabulary.value_counts()

source_vocabulary
International Classification of Diseases, Tenth Revision, Clinical Modification (NCHS)                    17772007
International Classification of Diseases, Ninth Revision, Clinical Modification, Volume 1 and 2 (NCHS)     7618737
Systematic Nomenclature of Medicine - Clinical Terms (IHTSDO)                                              1635791
OMOP Standardized Vocabularies                                                                               24605
Columbia International eHealth Laboratory (Columbia University)                                               4230
Nebraska Lexicon (UNMC)                                                                                        876
ICD-10 Procedure Coding System (CMS)                                                                           662
Healthcare Common Procedure Coding System (CMS)                                                                349
International Classification of Diseases for Oncology, Third Edition (WHO)                                      76
HemOnc                                                                                                          33
Current Procedural Terminology version 4 (AMA)                                                                   4
Name: count, dtype: int64

In [50]:
query = f"""
SELECT
    co.person_id, co.condition_start_datetime,
    c3.concept_name as condition_name,
    c4.concept_name as condition_type_name,
    c1.concept_name as visit_concept_name,
    vo.visit_concept_id,
    c2.concept_name as visit_type_concept_name,
    vo.visit_type_concept_id
FROM {dataset}.condition_occurrence co
JOIN {dataset}.visit_occurrence vo ON co.visit_occurrence_id = vo.visit_occurrence_id
JOIN {dataset}.concept c1 on vo.visit_concept_id = c1.concept_id
JOIN {dataset}.concept c2 on vo.visit_type_concept_id = c2.concept_id
JOIN {dataset}.concept c3 ON co.condition_concept_id = c3.concept_id
JOIN {dataset}.concept c4 ON co.condition_type_concept_id = c4.concept_id
WHERE co.person_id = 1000105
"""
temp_df = pandas_gbq.read_gbq(query)

Downloading:   0%|          |

Downloading: 100%|██████████|

In [12]:
with pd.option_context('display.max_colwidth', None, 'display.max_columns', None, ):
    display(temp_df.sort_values(by="condition_start_datetime").head(20))

NameError: name 'temp_df' is not defined

In [49]:
temp_df.visit_type_concept_name.value_counts()

visit_type_concept_name
Visit derived from EHR record    398
Name: count, dtype: int64

In [9]:
# Control cohort and their disease history
query = f"""
WITH target_cohort AS (
    SELECT DISTINCT person_id
    FROM {dataset}.condition_occurrence
    WHERE condition_concept_id IN (443597, 443612, 443611, 193782)
),

control_pool AS (
    SELECT person_id
    FROM {dataset}.condition_occurrence
    WHERE person_id NOT IN (SELECT person_id FROM target_cohort)
    ORDER BY FARM_FINGERPRINT(CONCAT(CAST(person_id AS STRING), 'seed123'))
    LIMIT 100
)

SELECT 
    co.person_id,
    -- 1. Disease Name
    c1.concept_name AS condition_name,
    co.condition_start_date,
    co.condition_end_date,
    -- 2. Type Name (e.g., "EHR Chief Complaint" or "Claim")
    c2.concept_name AS condition_type_name,
    -- 3. Status Name (e.g., "Final diagnosis")
    c3.concept_name AS condition_status_name,
    --c4.concept_name AS source_concept_name,
    v.vocabulary_name AS source_vocabulary,
    co.condition_source_value,
    --co.condition_occurrence_id,
    co.condition_concept_id,
    co.condition_type_concept_id,
    co.condition_status_concept_id
FROM {dataset}.condition_occurrence co
JOIN control_pool tc ON co.person_id = tc.person_id
-- Join for the main disease name
JOIN {dataset}.concept c1 ON co.condition_concept_id = c1.concept_id
-- Join for the record type
LEFT JOIN {dataset}.concept c2 ON co.condition_type_concept_id = c2.concept_id
-- Join for the clinical status
LEFT JOIN {dataset}.concept c3 ON co.condition_status_concept_id = c3.concept_id
-- Join 4: Source Concept Name
LEFT JOIN {dataset}.concept c4 ON co.condition_source_concept_id = c4.concept_id
-- Join 5: Vocabulary Name (e.g., identifying if it's ICD-9, ICD-10, etc.)
LEFT JOIN {dataset}.vocabulary v ON c4.vocabulary_id = v.vocabulary_id
ORDER BY co.person_id, co.condition_start_date;
"""

non_ckd_patients_disease_history = pandas_gbq.read_gbq(query)

Downloading:   0%|          |

Downloading:  95%|█████████▌|

Downloading: 100%|██████████|

In [10]:
non_ckd_patients_disease_history.head(5)

,person_id,condition_name,condition_start_date,condition_end_date,condition_type_name,condition_status_name,source_vocabulary,condition_source_value,condition_concept_id,condition_type_concept_id,condition_status_concept_id
0,2596882,Parkinson's disease,2010-06-10,NaT,EHR problem list entry,No matching concept,"International Classification of Diseases, Nint...",332.0,381270,38000245,0
1,2596882,Parkinson's disease,2010-06-10,NaT,EHR problem list entry,No matching concept,"International Classification of Diseases, Nint...",332.0,381270,38000245,0
2,2596882,Parkinson's disease,2010-06-10,NaT,EHR problem list entry,No matching concept,"International Classification of Diseases, Nint...",332.0,381270,38000245,0
3,2596882,Parkinson's disease,2010-06-10,NaT,EHR problem list entry,No matching concept,"International Classification of Diseases, Nint...",332.0,381270,38000245,0
4,2596882,Parkinson's disease,2010-06-10,NaT,EHR problem list entry,No matching concept,"International Classification of Diseases, Nint...",332.0,381270,38000245,0

## BigQuery Magic
We run into permission issues when using bigquery magic. We have to use the python client instead.

In [10]:
# Load bigquery magic
%load_ext google.cloud.bigquery

# Store params for BigQuery into a json so that we can use them with bigquery magic
bigquery_params = {"dataset": os.getenv("WORKSPACE_CDR"), "limit": 10}

In [ ]:
%%bigquery --params $bigquery_params
SELECT * FROM `dataset`.person LIMIT 5